id: QmPEgYdn4ocJC1YV3zoTArTstVsJGwg1ouz6nfmZsey4rm
description: ""
tags: []
source: .
trigger:
    type: https
    method: GET
    paths:
        - /hello2
domains:
    - somedomain
execution:
    timeout: 10s
    memory: 23MB
    call: triplo
