id: QmPK1s3pNYLi9ERiq3BDxKa4XosgWwFRQUydHUtz4YgpqB
description: This Function should work.
tags: []
source: libraries/testLibrary
trigger:
    type: https
    method: GET
    paths:
        - /goopath
domains:
    - GoodDomain
execution:
    timeout: 10s
    memory: 10MB
    call: ping
